### ISSUE TITLE
What tool will you use to convert DICOM to NIFTI? 

### ISSUE THREAD

**Issue by rwickens** [mtl-brainhack-school-2019/Nick-Hoang--Preprocess-analyze-task-based-fMRI-data#2]

**Comment by nhoang85** [comment]
I am hoping to use FSL to do the conversion :)

**Comment by bpinsard** [comment]
I thought we planned on using dcm2bids.

**Comment by alexapichet** [comment]
dcm2bids worked to organize the data 💯 

But to be more efficient in the brainhack-school he has already preprocessed data that are not in nifti that he could use ... If not planning to preprocess his newly organized data, he would need to convert the preprocessed data from his lab 

At this point my advice would be to just use openly accessible data for the remaining weeks to get familiar with the tools and wait when your master starts to preprocess your data ;)
